#ifndef GLOBALS_H
#define GLOBALS_H

const int SCREEN_WIDTH = 300;
const int SCREEN_HEIGHT = 300;
const int TEXTURE_WIDTH = 100;
const int TEXTURE_HEIGHT = 100;
const int BOARD_WIDTH_POSITIONS = SCREEN_WIDTH / TEXTURE_WIDTH;
const int BOARD_HEIGHT_POSITIONS = SCREEN_HEIGHT / TEXTURE_HEIGHT;

#endif
